server:
  port: 8255
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/text_es?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: cloud.entity


